apiVersion: rbac.authorization.k8s.io/v1 
kind: Role 
metadata:
  name: frontend-dev
  namespace: frontend 
rules:
  - apiGroups: [""]
    resources: ["pods", "deployments"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding
metadata:
  name: frontend-dev-roleBinding
  namespace: frontend
subjects:
- kind: User
  name: devuser2
  apiGroup: rbac.authorization.k8s.io
roleRef: 
  kind: Role 
  name: frontend-dev
  apiGroup: rbac.authorization.k8s.io